---

# Install Logstash/Configure and Run Logstash

- name: Copying Logstash Repo
  copy: src=logstash.repo dest=/etc/yum.repos.d/logstash.repo

- name: Install Logstash
  yum: name=logstash state=installed

- name: Configure Logstash input
  template: src=01-beats-input.conf.j2 dest=/etc/logstash/conf.d/02-beats-input.conf

- name: Configure Logstash syslog filter
  template: src=02-syslog-filter.conf.j2 dest=/etc/logstash/conf.d/10-syslog-filter.conf

- name: Configure Logstash ouput
  template: src=03-elasticsearch-output.conf.j2 dest=/etc/logstash/conf.d/30-elasticsearch-output.conf

- name: Restart Logstash
  service: name=logstash enabled=yes state=restarted
