---
- name: Installing OpenJDK
  yum: name=java-1.8.0-openjdk state=installed

- name: Import Elasticsearch public GPG key into rpm
  rpm_key: state=present key=http://packages.elastic.co/GPG-KEY-elasticsearch

- name: Copying yum repo for Elasticsearch
  copy: src=elasticsearch.repo dest=/etc/yum.repos.d/elasticsearch.repo owner=root group=root mode=0644

- name: Install Elasticsearch
  yum: name=elasticsearch state=installed

- name: Restrict to localhost
  lineinfile: 'dest=/etc/elasticsearch/elasticsearch.yml regexp=network.host line="network.host: 0.0.0.0"'

- name: Restart ElasticSearch
  service: name=elasticsearch enabled=yes state=restarted
